import { Link } from "react-router-dom"

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-950 text-white flex flex-col items-center justify-center px-6">

      <h1 className="text-6xl md:text-7xl font-extrabold text-center leading-tight max-w-5xl">
        Crack Interviews with
        <span className="text-blue-500"> AI Power</span>
      </h1>

      <p className="text-gray-400 text-xl text-center mt-6 max-w-2xl">
        Upload your resume, practice AI-generated interview questions,
        and improve your chances of getting hired.
      </p>

      <div className="flex gap-6 mt-10">

        <Link
          to="/register"
          className="bg-blue-600 hover:bg-blue-700 px-8 py-4 rounded-xl text-lg font-semibold transition"
        >
          Get Started
        </Link>

        <Link
          to="/login"
          className="border border-gray-600 hover:border-blue-500 px-8 py-4 rounded-xl text-lg transition"
        >
          Login
        </Link>

      </div>

      <div className="mt-20 grid md:grid-cols-3 gap-8 w-full max-w-6xl">

        <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
          <h2 className="text-2xl font-bold mb-3">AI Resume Analysis</h2>

          <p className="text-gray-400">
            Analyze your resume using AI and identify weak points instantly.
          </p>
        </div>

        <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
          <h2 className="text-2xl font-bold mb-3">Mock Interviews</h2>

          <p className="text-gray-400">
            Practice real interview questions generated by AI.
          </p>
        </div>

        <div className="bg-gray-900 p-6 rounded-2xl border border-gray-800">
          <h2 className="text-2xl font-bold mb-3">Performance Tracking</h2>

          <p className="text-gray-400">
            Track scores and improve your interview performance.
          </p>
        </div>

      </div>

    </div>
  )
}